ALTER DATABASE postgres			REFRESH COLLATION VERSION \gx
ALTER DATABASE template0		REFRESH COLLATION VERSION \gx
ALTER DATABASE template1		REFRESH COLLATION VERSION \gx

ALTER DATABASE acc_3_stat_archive	REFRESH COLLATION VERSION \gx
ALTER DATABASE stat_hrm_2		REFRESH COLLATION VERSION \gx
ALTER DATABASE trade_stat_archive	REFRESH COLLATION VERSION \gx

ALTER DATABASE stat_acc_3	 	REFRESH COLLATION VERSION \gx
ALTER DATABASE stat_acc_zf		REFRESH COLLATION VERSION \gx
ALTER DATABASE stat_alfa_5		REFRESH COLLATION VERSION \gx
ALTER DATABASE stat_hrm_3		REFRESH COLLATION VERSION \gx

ALTER DATABASE stat_acc_other		REFRESH COLLATION VERSION \gx
ALTER DATABASE stat_alfa_invent		REFRESH COLLATION VERSION \gx
ALTER DATABASE stat_erp_demo		REFRESH COLLATION VERSION \gx
ALTER DATABASE test			REFRESH COLLATION VERSION \gx
ALTER DATABASE test_stat_acc_3		REFRESH COLLATION VERSION \gx
ALTER DATABASE test_stat_alfa		REFRESH COLLATION VERSION \gx
ALTER DATABASE test_stat_hrm_3	 	REFRESH COLLATION VERSION \gx
ALTER DATABASE test_sync_stat_acc_3	REFRESH COLLATION VERSION \gx
ALTER DATABASE test_sync_stat_alfa	REFRESH COLLATION VERSION \gx
